kind: Service
apiVersion: v1
metadata:
  name: shorter
  labels:
    app: shorter
spec:
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: shorter
  type: ClusterIP